---
- hosts: all

  tasks: 

    - name: Get temps on provided hosts
      raw: paste <(cat /sys/class/thermal/thermal_zone*/type) <(cat /sys/class/thermal/thermal_zone*/temp) | column -s $'\t' -t | sed 's/\(.\)..$/.\1°C/'
      register: temps

    - debug:
        var: temps.stdout_lines
