---
- hosts: all
  become: True
  
  tasks:
  # The following shell commands are taken directly from:
  # https://restic.readthedocs.io/en/stable/080_examples.html#full-backup-without-root
  - name: Configure restic user
    shell: |
      useradd -m restic
      mkdir ~restic/bin
      curl -L https://github.com/restic/restic/releases/download/v0.9.6/restic_0.9.6_linux_arm64.bz2 | bunzip2 > ~restic/bin/restic
      chown root:restic ~restic/bin/restic
      chmod 750 ~restic/bin/restic
      setcap cap_dac_read_search=+ep ~restic/bin/restic
