---
- hosts: all
  become: true

  tasks:
    - name: Update apt cache (apt update)
      apt:
        update_cache: yes
    
    - name: Upgrade all packages to the latest version (full-upgrade)
      apt:
        # Raspberry Pi OS recommends doing a 'apt full-upgrade' instead of just an
        # 'apt upgrade'
        # https://www.raspberrypi.org/documentation/raspbian/updating.md
        upgrade: full
    
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
    
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
